/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ConsoleConsoleRouteImport } from './routes/console/_console'
import { Route as ConsoleSignInRouteImport } from './routes/console/sign-in'
import { Route as AppBillingIndexRouteImport } from './routes/_app/billing/index'
import { Route as AppBillingInvoiceIdRouteImport } from './routes/_app/billing/$invoiceId'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppCustomersNewRouteImport } from './routes/_app/customers/new'
import { Route as AppEncountersEncounterIdRouteImport } from './routes/_app/encounters/$encounterId'
import { Route as ConsoleConsoleIndexRouteImport } from './routes/console/_console/index'
import { Route as ConsoleConsoleAdministratorsRouteImport } from './routes/console/_console/administrators'
import { Route as ConsoleConsoleNewClinicRouteImport } from './routes/console/_console/new-clinic'
import { Route as AppCustomersCustomerIdIndexRouteImport } from './routes/_app/customers/$customerId.index'
import { Route as AppCustomersCustomerIdHistoryRouteImport } from './routes/_app/customers/$customerId.history'
import { Route as ConsoleConsoleClinicsTenantIdModulesRouteImport } from './routes/console/_console/clinics/$tenantId.modules'
import { Route as ConsoleConsoleClinicsTenantIdParametersRouteImport } from './routes/console/_console/clinics/$tenantId.parameters'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ConsoleConsoleRoute = ConsoleConsoleRouteImport.update({
  id: '/console/_console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleSignInRoute = ConsoleSignInRouteImport.update({
  id: '/console/sign-in',
  path: '/console/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingInvoiceIdRoute = AppBillingInvoiceIdRouteImport.update({
  id: '/billing/$invoiceId',
  path: '/billing/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEncountersEncounterIdRoute =
  AppEncountersEncounterIdRouteImport.update({
    id: '/encounters/$encounterId',
    path: '/encounters/$encounterId',
    getParentRoute: () => AppRoute,
  } as any)
const ConsoleConsoleIndexRoute = ConsoleConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleConsoleRoute,
} as any)
const ConsoleConsoleAdministratorsRoute =
  ConsoleConsoleAdministratorsRouteImport.update({
    id: '/administrators',
    path: '/administrators',
    getParentRoute: () => ConsoleConsoleRoute,
  } as any)
const ConsoleConsoleNewClinicRoute = ConsoleConsoleNewClinicRouteImport.update({
  id: '/new-clinic',
  path: '/new-clinic',
  getParentRoute: () => ConsoleConsoleRoute,
} as any)
const AppCustomersCustomerIdIndexRoute =
  AppCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCustomersCustomerIdHistoryRoute =
  AppCustomersCustomerIdHistoryRouteImport.update({
    id: '/customers/$customerId/history',
    path: '/customers/$customerId/history',
    getParentRoute: () => AppRoute,
  } as any)
const ConsoleConsoleClinicsTenantIdModulesRoute =
  ConsoleConsoleClinicsTenantIdModulesRouteImport.update({
    id: '/clinics/$tenantId/modules',
    path: '/clinics/$tenantId/modules',
    getParentRoute: () => ConsoleConsoleRoute,
  } as any)
const ConsoleConsoleClinicsTenantIdParametersRoute =
  ConsoleConsoleClinicsTenantIdParametersRouteImport.update({
    id: '/clinics/$tenantId/parameters',
    path: '/clinics/$tenantId/parameters',
    getParentRoute: () => ConsoleConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/console': typeof ConsoleConsoleRouteWithChildren
  '/console/sign-in': typeof ConsoleSignInRoute
  '/billing/$invoiceId': typeof AppBillingInvoiceIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/encounters/$encounterId': typeof AppEncountersEncounterIdRoute
  '/console/administrators': typeof ConsoleConsoleAdministratorsRoute
  '/console/new-clinic': typeof ConsoleConsoleNewClinicRoute
  '/billing/': typeof AppBillingIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/console/': typeof ConsoleConsoleIndexRoute
  '/customers/$customerId/history': typeof AppCustomersCustomerIdHistoryRoute
  '/customers/$customerId/': typeof AppCustomersCustomerIdIndexRoute
  '/console/clinics/$tenantId/modules': typeof ConsoleConsoleClinicsTenantIdModulesRoute
  '/console/clinics/$tenantId/parameters': typeof ConsoleConsoleClinicsTenantIdParametersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/console/sign-in': typeof ConsoleSignInRoute
  '/': typeof AppIndexRoute
  '/billing/$invoiceId': typeof AppBillingInvoiceIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/encounters/$encounterId': typeof AppEncountersEncounterIdRoute
  '/console/administrators': typeof ConsoleConsoleAdministratorsRoute
  '/console/new-clinic': typeof ConsoleConsoleNewClinicRoute
  '/billing': typeof AppBillingIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/console': typeof ConsoleConsoleIndexRoute
  '/customers/$customerId/history': typeof AppCustomersCustomerIdHistoryRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdIndexRoute
  '/console/clinics/$tenantId/modules': typeof ConsoleConsoleClinicsTenantIdModulesRoute
  '/console/clinics/$tenantId/parameters': typeof ConsoleConsoleClinicsTenantIdParametersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/console/_console': typeof ConsoleConsoleRouteWithChildren
  '/console/sign-in': typeof ConsoleSignInRoute
  '/_app/': typeof AppIndexRoute
  '/_app/billing/$invoiceId': typeof AppBillingInvoiceIdRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/encounters/$encounterId': typeof AppEncountersEncounterIdRoute
  '/console/_console/administrators': typeof ConsoleConsoleAdministratorsRoute
  '/console/_console/new-clinic': typeof ConsoleConsoleNewClinicRoute
  '/_app/billing/': typeof AppBillingIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/console/_console/': typeof ConsoleConsoleIndexRoute
  '/_app/customers/$customerId/history': typeof AppCustomersCustomerIdHistoryRoute
  '/_app/customers/$customerId/': typeof AppCustomersCustomerIdIndexRoute
  '/console/_console/clinics/$tenantId/modules': typeof ConsoleConsoleClinicsTenantIdModulesRoute
  '/console/_console/clinics/$tenantId/parameters': typeof ConsoleConsoleClinicsTenantIdParametersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/schedule'
    | '/settings'
    | '/console'
    | '/console/sign-in'
    | '/billing/$invoiceId'
    | '/customers/new'
    | '/encounters/$encounterId'
    | '/console/administrators'
    | '/console/new-clinic'
    | '/billing/'
    | '/customers/'
    | '/console/'
    | '/customers/$customerId/history'
    | '/customers/$customerId/'
    | '/console/clinics/$tenantId/modules'
    | '/console/clinics/$tenantId/parameters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/schedule'
    | '/settings'
    | '/console/sign-in'
    | '/'
    | '/billing/$invoiceId'
    | '/customers/new'
    | '/encounters/$encounterId'
    | '/console/administrators'
    | '/console/new-clinic'
    | '/billing'
    | '/customers'
    | '/console'
    | '/customers/$customerId/history'
    | '/customers/$customerId'
    | '/console/clinics/$tenantId/modules'
    | '/console/clinics/$tenantId/parameters'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/schedule'
    | '/_app/settings'
    | '/console/_console'
    | '/console/sign-in'
    | '/_app/'
    | '/_app/billing/$invoiceId'
    | '/_app/customers/new'
    | '/_app/encounters/$encounterId'
    | '/console/_console/administrators'
    | '/console/_console/new-clinic'
    | '/_app/billing/'
    | '/_app/customers/'
    | '/console/_console/'
    | '/_app/customers/$customerId/history'
    | '/_app/customers/$customerId/'
    | '/console/_console/clinics/$tenantId/modules'
    | '/console/_console/clinics/$tenantId/parameters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ConsoleConsoleRoute: typeof ConsoleConsoleRouteWithChildren
  ConsoleSignInRoute: typeof ConsoleSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/console/_console': {
      id: '/console/_console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/sign-in': {
      id: '/console/sign-in'
      path: '/console/sign-in'
      fullPath: '/console/sign-in'
      preLoaderRoute: typeof ConsoleSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/billing/': {
      id: '/_app/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing/$invoiceId': {
      id: '/_app/billing/$invoiceId'
      path: '/billing/$invoiceId'
      fullPath: '/billing/$invoiceId'
      preLoaderRoute: typeof AppBillingInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/encounters/$encounterId': {
      id: '/_app/encounters/$encounterId'
      path: '/encounters/$encounterId'
      fullPath: '/encounters/$encounterId'
      preLoaderRoute: typeof AppEncountersEncounterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/console/_console/': {
      id: '/console/_console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleConsoleIndexRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/console/_console/administrators': {
      id: '/console/_console/administrators'
      path: '/administrators'
      fullPath: '/console/administrators'
      preLoaderRoute: typeof ConsoleConsoleAdministratorsRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/console/_console/new-clinic': {
      id: '/console/_console/new-clinic'
      path: '/new-clinic'
      fullPath: '/console/new-clinic'
      preLoaderRoute: typeof ConsoleConsoleNewClinicRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/_app/customers/$customerId/': {
      id: '/_app/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof AppCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId/history': {
      id: '/_app/customers/$customerId/history'
      path: '/customers/$customerId/history'
      fullPath: '/customers/$customerId/history'
      preLoaderRoute: typeof AppCustomersCustomerIdHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/console/_console/clinics/$tenantId/modules': {
      id: '/console/_console/clinics/$tenantId/modules'
      path: '/clinics/$tenantId/modules'
      fullPath: '/console/clinics/$tenantId/modules'
      preLoaderRoute: typeof ConsoleConsoleClinicsTenantIdModulesRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/console/_console/clinics/$tenantId/parameters': {
      id: '/console/_console/clinics/$tenantId/parameters'
      path: '/clinics/$tenantId/parameters'
      fullPath: '/console/clinics/$tenantId/parameters'
      preLoaderRoute: typeof ConsoleConsoleClinicsTenantIdParametersRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
  }
}

interface AppRouteChildren {
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBillingInvoiceIdRoute: typeof AppBillingInvoiceIdRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppEncountersEncounterIdRoute: typeof AppEncountersEncounterIdRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppCustomersCustomerIdHistoryRoute: typeof AppCustomersCustomerIdHistoryRoute
  AppCustomersCustomerIdIndexRoute: typeof AppCustomersCustomerIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBillingInvoiceIdRoute: AppBillingInvoiceIdRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppEncountersEncounterIdRoute: AppEncountersEncounterIdRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppCustomersCustomerIdHistoryRoute: AppCustomersCustomerIdHistoryRoute,
  AppCustomersCustomerIdIndexRoute: AppCustomersCustomerIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ConsoleConsoleRouteChildren {
  ConsoleConsoleAdministratorsRoute: typeof ConsoleConsoleAdministratorsRoute
  ConsoleConsoleNewClinicRoute: typeof ConsoleConsoleNewClinicRoute
  ConsoleConsoleIndexRoute: typeof ConsoleConsoleIndexRoute
  ConsoleConsoleClinicsTenantIdModulesRoute: typeof ConsoleConsoleClinicsTenantIdModulesRoute
  ConsoleConsoleClinicsTenantIdParametersRoute: typeof ConsoleConsoleClinicsTenantIdParametersRoute
}

const ConsoleConsoleRouteChildren: ConsoleConsoleRouteChildren = {
  ConsoleConsoleAdministratorsRoute: ConsoleConsoleAdministratorsRoute,
  ConsoleConsoleNewClinicRoute: ConsoleConsoleNewClinicRoute,
  ConsoleConsoleIndexRoute: ConsoleConsoleIndexRoute,
  ConsoleConsoleClinicsTenantIdModulesRoute:
    ConsoleConsoleClinicsTenantIdModulesRoute,
  ConsoleConsoleClinicsTenantIdParametersRoute:
    ConsoleConsoleClinicsTenantIdParametersRoute,
}

const ConsoleConsoleRouteWithChildren = ConsoleConsoleRoute._addFileChildren(
  ConsoleConsoleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ConsoleConsoleRoute: ConsoleConsoleRouteWithChildren,
  ConsoleSignInRoute: ConsoleSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
