/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppComissoesRouteImport } from './routes/_app/comissoes'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as ConsoleConsoleRouteImport } from './routes/console/_console'
import { Route as ConsoleEntrarRouteImport } from './routes/console/entrar'
import { Route as AppAtendimentosEncounterIdRouteImport } from './routes/_app/atendimentos/$encounterId'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes/index'
import { Route as AppClientesNovoRouteImport } from './routes/_app/clientes/novo'
import { Route as AppEstoqueIndexRouteImport } from './routes/_app/estoque/index'
import { Route as AppEstoqueProductIdRouteImport } from './routes/_app/estoque/$productId'
import { Route as AppFinanceiroIndexRouteImport } from './routes/_app/financeiro/index'
import { Route as AppFinanceiroInvoiceIdRouteImport } from './routes/_app/financeiro/$invoiceId'
import { Route as ConsoleConsoleIndexRouteImport } from './routes/console/_console/index'
import { Route as ConsoleConsoleAdministradoresRouteImport } from './routes/console/_console/administradores'
import { Route as ConsoleConsoleNovaClinicaRouteImport } from './routes/console/_console/nova-clinica'
import { Route as AppClientesCustomerIdIndexRouteImport } from './routes/_app/clientes/$customerId.index'
import { Route as AppClientesCustomerIdHistoricoRouteImport } from './routes/_app/clientes/$customerId.historico'
import { Route as ConsoleConsoleClinicasTenantIdModulosRouteImport } from './routes/console/_console/clinicas/$tenantId.modulos'
import { Route as ConsoleConsoleClinicasTenantIdParametrosRouteImport } from './routes/console/_console/clinicas/$tenantId.parametros'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppComissoesRoute = AppComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const ConsoleConsoleRoute = ConsoleConsoleRouteImport.update({
  id: '/console/_console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleEntrarRoute = ConsoleEntrarRouteImport.update({
  id: '/console/entrar',
  path: '/console/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAtendimentosEncounterIdRoute =
  AppAtendimentosEncounterIdRouteImport.update({
    id: '/atendimentos/$encounterId',
    path: '/atendimentos/$encounterId',
    getParentRoute: () => AppRoute,
  } as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueIndexRoute = AppEstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueProductIdRoute = AppEstoqueProductIdRouteImport.update({
  id: '/estoque/$productId',
  path: '/estoque/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroIndexRoute = AppFinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroInvoiceIdRoute = AppFinanceiroInvoiceIdRouteImport.update({
  id: '/financeiro/$invoiceId',
  path: '/financeiro/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const ConsoleConsoleIndexRoute = ConsoleConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleConsoleRoute,
} as any)
const ConsoleConsoleAdministradoresRoute =
  ConsoleConsoleAdministradoresRouteImport.update({
    id: '/administradores',
    path: '/administradores',
    getParentRoute: () => ConsoleConsoleRoute,
  } as any)
const ConsoleConsoleNovaClinicaRoute =
  ConsoleConsoleNovaClinicaRouteImport.update({
    id: '/nova-clinica',
    path: '/nova-clinica',
    getParentRoute: () => ConsoleConsoleRoute,
  } as any)
const AppClientesCustomerIdIndexRoute =
  AppClientesCustomerIdIndexRouteImport.update({
    id: '/clientes/$customerId/',
    path: '/clientes/$customerId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppClientesCustomerIdHistoricoRoute =
  AppClientesCustomerIdHistoricoRouteImport.update({
    id: '/clientes/$customerId/historico',
    path: '/clientes/$customerId/historico',
    getParentRoute: () => AppRoute,
  } as any)
const ConsoleConsoleClinicasTenantIdModulosRoute =
  ConsoleConsoleClinicasTenantIdModulosRouteImport.update({
    id: '/clinicas/$tenantId/modulos',
    path: '/clinicas/$tenantId/modulos',
    getParentRoute: () => ConsoleConsoleRoute,
  } as any)
const ConsoleConsoleClinicasTenantIdParametrosRoute =
  ConsoleConsoleClinicasTenantIdParametrosRouteImport.update({
    id: '/clinicas/$tenantId/parametros',
    path: '/clinicas/$tenantId/parametros',
    getParentRoute: () => ConsoleConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/comissoes': typeof AppComissoesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/console': typeof ConsoleConsoleRouteWithChildren
  '/console/entrar': typeof ConsoleEntrarRoute
  '/atendimentos/$encounterId': typeof AppAtendimentosEncounterIdRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/estoque/$productId': typeof AppEstoqueProductIdRoute
  '/financeiro/$invoiceId': typeof AppFinanceiroInvoiceIdRoute
  '/console/administradores': typeof ConsoleConsoleAdministradoresRoute
  '/console/nova-clinica': typeof ConsoleConsoleNovaClinicaRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/estoque/': typeof AppEstoqueIndexRoute
  '/financeiro/': typeof AppFinanceiroIndexRoute
  '/console/': typeof ConsoleConsoleIndexRoute
  '/clientes/$customerId/historico': typeof AppClientesCustomerIdHistoricoRoute
  '/clientes/$customerId/': typeof AppClientesCustomerIdIndexRoute
  '/console/clinicas/$tenantId/modulos': typeof ConsoleConsoleClinicasTenantIdModulosRoute
  '/console/clinicas/$tenantId/parametros': typeof ConsoleConsoleClinicasTenantIdParametrosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/comissoes': typeof AppComissoesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/console/entrar': typeof ConsoleEntrarRoute
  '/': typeof AppIndexRoute
  '/atendimentos/$encounterId': typeof AppAtendimentosEncounterIdRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/estoque/$productId': typeof AppEstoqueProductIdRoute
  '/financeiro/$invoiceId': typeof AppFinanceiroInvoiceIdRoute
  '/console/administradores': typeof ConsoleConsoleAdministradoresRoute
  '/console/nova-clinica': typeof ConsoleConsoleNovaClinicaRoute
  '/clientes': typeof AppClientesIndexRoute
  '/estoque': typeof AppEstoqueIndexRoute
  '/financeiro': typeof AppFinanceiroIndexRoute
  '/console': typeof ConsoleConsoleIndexRoute
  '/clientes/$customerId/historico': typeof AppClientesCustomerIdHistoricoRoute
  '/clientes/$customerId': typeof AppClientesCustomerIdIndexRoute
  '/console/clinicas/$tenantId/modulos': typeof ConsoleConsoleClinicasTenantIdModulosRoute
  '/console/clinicas/$tenantId/parametros': typeof ConsoleConsoleClinicasTenantIdParametrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/comissoes': typeof AppComissoesRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/console/_console': typeof ConsoleConsoleRouteWithChildren
  '/console/entrar': typeof ConsoleEntrarRoute
  '/_app/': typeof AppIndexRoute
  '/_app/atendimentos/$encounterId': typeof AppAtendimentosEncounterIdRoute
  '/_app/clientes/novo': typeof AppClientesNovoRoute
  '/_app/estoque/$productId': typeof AppEstoqueProductIdRoute
  '/_app/financeiro/$invoiceId': typeof AppFinanceiroInvoiceIdRoute
  '/console/_console/administradores': typeof ConsoleConsoleAdministradoresRoute
  '/console/_console/nova-clinica': typeof ConsoleConsoleNovaClinicaRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/estoque/': typeof AppEstoqueIndexRoute
  '/_app/financeiro/': typeof AppFinanceiroIndexRoute
  '/console/_console/': typeof ConsoleConsoleIndexRoute
  '/_app/clientes/$customerId/historico': typeof AppClientesCustomerIdHistoricoRoute
  '/_app/clientes/$customerId/': typeof AppClientesCustomerIdIndexRoute
  '/console/_console/clinicas/$tenantId/modulos': typeof ConsoleConsoleClinicasTenantIdModulosRoute
  '/console/_console/clinicas/$tenantId/parametros': typeof ConsoleConsoleClinicasTenantIdParametrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/comissoes'
    | '/configuracoes'
    | '/console'
    | '/console/entrar'
    | '/atendimentos/$encounterId'
    | '/clientes/novo'
    | '/estoque/$productId'
    | '/financeiro/$invoiceId'
    | '/console/administradores'
    | '/console/nova-clinica'
    | '/clientes/'
    | '/estoque/'
    | '/financeiro/'
    | '/console/'
    | '/clientes/$customerId/historico'
    | '/clientes/$customerId/'
    | '/console/clinicas/$tenantId/modulos'
    | '/console/clinicas/$tenantId/parametros'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agenda'
    | '/comissoes'
    | '/configuracoes'
    | '/console/entrar'
    | '/'
    | '/atendimentos/$encounterId'
    | '/clientes/novo'
    | '/estoque/$productId'
    | '/financeiro/$invoiceId'
    | '/console/administradores'
    | '/console/nova-clinica'
    | '/clientes'
    | '/estoque'
    | '/financeiro'
    | '/console'
    | '/clientes/$customerId/historico'
    | '/clientes/$customerId'
    | '/console/clinicas/$tenantId/modulos'
    | '/console/clinicas/$tenantId/parametros'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/agenda'
    | '/_app/comissoes'
    | '/_app/configuracoes'
    | '/console/_console'
    | '/console/entrar'
    | '/_app/'
    | '/_app/atendimentos/$encounterId'
    | '/_app/clientes/novo'
    | '/_app/estoque/$productId'
    | '/_app/financeiro/$invoiceId'
    | '/console/_console/administradores'
    | '/console/_console/nova-clinica'
    | '/_app/clientes/'
    | '/_app/estoque/'
    | '/_app/financeiro/'
    | '/console/_console/'
    | '/_app/clientes/$customerId/historico'
    | '/_app/clientes/$customerId/'
    | '/console/_console/clinicas/$tenantId/modulos'
    | '/console/_console/clinicas/$tenantId/parametros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ConsoleConsoleRoute: typeof ConsoleConsoleRouteWithChildren
  ConsoleEntrarRoute: typeof ConsoleEntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comissoes': {
      id: '/_app/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AppComissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/console/_console': {
      id: '/console/_console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/entrar': {
      id: '/console/entrar'
      path: '/console/entrar'
      fullPath: '/console/entrar'
      preLoaderRoute: typeof ConsoleEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/atendimentos/$encounterId': {
      id: '/_app/atendimentos/$encounterId'
      path: '/atendimentos/$encounterId'
      fullPath: '/atendimentos/$encounterId'
      preLoaderRoute: typeof AppAtendimentosEncounterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/novo': {
      id: '/_app/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/': {
      id: '/_app/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AppEstoqueIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/$productId': {
      id: '/_app/estoque/$productId'
      path: '/estoque/$productId'
      fullPath: '/estoque/$productId'
      preLoaderRoute: typeof AppEstoqueProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/': {
      id: '/_app/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AppFinanceiroIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/$invoiceId': {
      id: '/_app/financeiro/$invoiceId'
      path: '/financeiro/$invoiceId'
      fullPath: '/financeiro/$invoiceId'
      preLoaderRoute: typeof AppFinanceiroInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/console/_console/': {
      id: '/console/_console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleConsoleIndexRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/console/_console/administradores': {
      id: '/console/_console/administradores'
      path: '/administradores'
      fullPath: '/console/administradores'
      preLoaderRoute: typeof ConsoleConsoleAdministradoresRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/console/_console/nova-clinica': {
      id: '/console/_console/nova-clinica'
      path: '/nova-clinica'
      fullPath: '/console/nova-clinica'
      preLoaderRoute: typeof ConsoleConsoleNovaClinicaRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/_app/clientes/$customerId/': {
      id: '/_app/clientes/$customerId/'
      path: '/clientes/$customerId'
      fullPath: '/clientes/$customerId/'
      preLoaderRoute: typeof AppClientesCustomerIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$customerId/historico': {
      id: '/_app/clientes/$customerId/historico'
      path: '/clientes/$customerId/historico'
      fullPath: '/clientes/$customerId/historico'
      preLoaderRoute: typeof AppClientesCustomerIdHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/console/_console/clinicas/$tenantId/modulos': {
      id: '/console/_console/clinicas/$tenantId/modulos'
      path: '/clinicas/$tenantId/modulos'
      fullPath: '/console/clinicas/$tenantId/modulos'
      preLoaderRoute: typeof ConsoleConsoleClinicasTenantIdModulosRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/console/_console/clinicas/$tenantId/parametros': {
      id: '/console/_console/clinicas/$tenantId/parametros'
      path: '/clinicas/$tenantId/parametros'
      fullPath: '/console/clinicas/$tenantId/parametros'
      preLoaderRoute: typeof ConsoleConsoleClinicasTenantIdParametrosRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppComissoesRoute: typeof AppComissoesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAtendimentosEncounterIdRoute: typeof AppAtendimentosEncounterIdRoute
  AppClientesNovoRoute: typeof AppClientesNovoRoute
  AppEstoqueProductIdRoute: typeof AppEstoqueProductIdRoute
  AppFinanceiroInvoiceIdRoute: typeof AppFinanceiroInvoiceIdRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppEstoqueIndexRoute: typeof AppEstoqueIndexRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
  AppClientesCustomerIdHistoricoRoute: typeof AppClientesCustomerIdHistoricoRoute
  AppClientesCustomerIdIndexRoute: typeof AppClientesCustomerIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppComissoesRoute: AppComissoesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppIndexRoute: AppIndexRoute,
  AppAtendimentosEncounterIdRoute: AppAtendimentosEncounterIdRoute,
  AppClientesNovoRoute: AppClientesNovoRoute,
  AppEstoqueProductIdRoute: AppEstoqueProductIdRoute,
  AppFinanceiroInvoiceIdRoute: AppFinanceiroInvoiceIdRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppEstoqueIndexRoute: AppEstoqueIndexRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
  AppClientesCustomerIdHistoricoRoute: AppClientesCustomerIdHistoricoRoute,
  AppClientesCustomerIdIndexRoute: AppClientesCustomerIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ConsoleConsoleRouteChildren {
  ConsoleConsoleAdministradoresRoute: typeof ConsoleConsoleAdministradoresRoute
  ConsoleConsoleNovaClinicaRoute: typeof ConsoleConsoleNovaClinicaRoute
  ConsoleConsoleIndexRoute: typeof ConsoleConsoleIndexRoute
  ConsoleConsoleClinicasTenantIdModulosRoute: typeof ConsoleConsoleClinicasTenantIdModulosRoute
  ConsoleConsoleClinicasTenantIdParametrosRoute: typeof ConsoleConsoleClinicasTenantIdParametrosRoute
}

const ConsoleConsoleRouteChildren: ConsoleConsoleRouteChildren = {
  ConsoleConsoleAdministradoresRoute: ConsoleConsoleAdministradoresRoute,
  ConsoleConsoleNovaClinicaRoute: ConsoleConsoleNovaClinicaRoute,
  ConsoleConsoleIndexRoute: ConsoleConsoleIndexRoute,
  ConsoleConsoleClinicasTenantIdModulosRoute:
    ConsoleConsoleClinicasTenantIdModulosRoute,
  ConsoleConsoleClinicasTenantIdParametrosRoute:
    ConsoleConsoleClinicasTenantIdParametrosRoute,
}

const ConsoleConsoleRouteWithChildren = ConsoleConsoleRoute._addFileChildren(
  ConsoleConsoleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ConsoleConsoleRoute: ConsoleConsoleRouteWithChildren,
  ConsoleEntrarRoute: ConsoleEntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
